import { usePreferencesStore } from '@/store/preferences'

type Language = 'EN' | 'VI'

const copy = {
  EN: {
    brand: 'BadBook',
    accountActions: 'Administrator',
    searchPlaceholder: 'Search users, bookings, payments...',
    signInTitle: 'Portal sign in',
    signInVisualTitle: 'Operate the badminton platform with one command center.',
    signInVisualDesc:
      'Review courts, bookings, transactions and moderation from a single dashboard.',
    email: 'Email',
    password: 'Password',
    login: 'Sign in',
    forgotPassword: 'Forgot password?',
    logout: 'Sign out',
    loading: 'Loading...',
    loginError: 'Invalid email or password',
    selectRoleTitle: 'Choose a portal',
    selectRoleDesc:
      'You have access to multiple portals. Select one to continue.',
    adminPortal: 'Admin Portal',
    adminPortalDesc:
      'Manage venues, users, invoices and platform settings.',
    venuePortal: 'Venue Manager Portal',
    venuePortalDesc:
      'Manage your courts, bookings, products and reviews.',
    backHome: 'Back to dashboard',
    notFoundTitle: '404',
    notFoundHeading: 'Page not found',
    notFoundDesc: 'The page you requested does not exist in the portal.',
    collapseSidebar: 'Collapse sidebar',
    overviewGroup: 'Overview',
    accessGroup: 'Access',
    operationsGroup: 'Operations',
    platformGroup: 'Platform',
    navOverview: 'Dashboard',
    navUsers: 'Users',
    navRbac: 'Roles & access',
    navEmployerVerification: 'Court verification',
    navJobModeration: 'Booking moderation',
    navPackages: 'Packages',
    navPayments: 'Payments',
    navAiConfig: 'AI assistant config',
    navSettings: 'System settings',
    navAuditLogs: 'Audit logs',
    dashboardTitle: 'Operations overview',
    activeUsers: 'Active users',
    newCandidates: 'New players',
    newEmployers: 'New venue owners',
    jobsToday: 'Bookings today',
    monthlyRevenue: 'Monthly revenue',
    aiQueue: 'Support queue',
    userGrowth: 'User growth',
    revenueChart: 'Revenue trend',
    pendingEmployers: 'Venues pending review',
    recentTransactions: 'Recent transactions',
    usersTitle: 'User management',
    roleCandidate: 'Player',
    roleEmployer: 'Venue owner',
    actionLock: 'Lock',
    actionUnlock: 'Unlock',
    rbacTitle: 'Role-based access control',
    rbacRoles: 'Roles',
    rbacCreateRole: 'Create role',
    rbacRoleName: 'Role name',
    rbacRoleDesc: 'Description',
    rbacResource: 'Resource',
    rbacActions: 'Actions',
    rbacSave: 'Save permissions',
    rbacReset: 'Reset',
    employerVerificationTitle: 'Venue verification',
    jobModerationTitle: 'Booking moderation',
    packagesTitle: 'Service packages',
    paymentsTitle: 'Payment tracking',
    aiTitle: 'AI assistant settings',
    aiSave: 'Save configuration',
    aiQueueStats: 'Queue statistics',
    systemTitle: 'System settings',
    systemSave: 'Save settings',
    auditLogsTitle: 'Audit logs',
    actionApprove: 'Approve',
    actionReject: 'Reject',
    actionHide: 'Hide',
    allStatus: 'All statuses',
    allActions: 'All actions',
  },
  VI: {
    brand: 'BadBook',
    accountActions: 'Quản trị viên',
    searchPlaceholder: 'Tìm người dùng, booking, thanh toán...',
    signInTitle: 'Đăng nhập cổng quản lý',
    signInVisualTitle: 'Điều hành nền tảng cầu lông trong một bảng điều khiển.',
    signInVisualDesc:
      'Kiểm duyệt sân, booking, giao dịch và vận hành từ một giao diện duy nhất.',
    email: 'Email',
    password: 'Mật khẩu',
    login: 'Đăng nhập',
    forgotPassword: 'Quên mật khẩu?',
    logout: 'Đăng xuất',
    loading: 'Đang xử lý...',
    loginError: 'Email hoặc mật khẩu không đúng',
    selectRoleTitle: 'Chọn giao diện',
    selectRoleDesc:
      'Tài khoản của bạn có nhiều vai trò. Chọn giao diện để tiếp tục.',
    adminPortal: 'Cổng Quản trị',
    adminPortalDesc:
      'Quản lý sân, người dùng, hóa đơn và cài đặt hệ thống.',
    venuePortal: 'Cổng Quản lý Sân',
    venuePortalDesc:
      'Quản lý sân, booking, sản phẩm và đánh giá.',
    backHome: 'Về trang quản trị',
    notFoundTitle: '404',
    notFoundHeading: 'Không tìm thấy trang',
    notFoundDesc:
      'Trang bạn yêu cầu không tồn tại trong cổng quản lý hiện tại.',
    collapseSidebar: 'Thu gọn menu',
    overviewGroup: 'Tổng quan',
    accessGroup: 'Phân quyền',
    operationsGroup: 'Vận hành',
    platformGroup: 'Hệ thống',
    navOverview: 'Bảng điều khiển',
    navUsers: 'Người dùng',
    navRbac: 'Vai trò & quyền',
    navEmployerVerification: 'Duyệt sân',
    navJobModeration: 'Kiểm duyệt booking',
    navPackages: 'Gói dịch vụ',
    navPayments: 'Thanh toán',
    navAiConfig: 'Cấu hình AI',
    navSettings: 'Thiết lập hệ thống',
    navAuditLogs: 'Nhật ký hoạt động',
    dashboardTitle: 'Tổng quan vận hành',
    activeUsers: 'Người dùng hoạt động',
    newCandidates: 'Người chơi mới',
    newEmployers: 'Chủ sân mới',
    jobsToday: 'Booking hôm nay',
    monthlyRevenue: 'Doanh thu tháng',
    aiQueue: 'Hàng đợi hỗ trợ',
    userGrowth: 'Tăng trưởng người dùng',
    revenueChart: 'Xu hướng doanh thu',
    pendingEmployers: 'Sân chờ kiểm duyệt',
    recentTransactions: 'Giao dịch gần đây',
    usersTitle: 'Quản lý người dùng',
    roleCandidate: 'Người chơi',
    roleEmployer: 'Chủ sân',
    actionLock: 'Khóa',
    actionUnlock: 'Mở khóa',
    rbacTitle: 'Phân quyền theo vai trò',
    rbacRoles: 'Danh sách vai trò',
    rbacCreateRole: 'Tạo vai trò',
    rbacRoleName: 'Tên vai trò',
    rbacRoleDesc: 'Mô tả',
    rbacResource: 'Tài nguyên',
    rbacActions: 'Hành động',
    rbacSave: 'Lưu quyền',
    rbacReset: 'Đặt lại',
    employerVerificationTitle: 'Duyệt sân đối tác',
    jobModerationTitle: 'Kiểm duyệt booking',
    packagesTitle: 'Gói dịch vụ',
    paymentsTitle: 'Theo dõi thanh toán',
    aiTitle: 'Thiết lập trợ lý AI',
    aiSave: 'Lưu cấu hình',
    aiQueueStats: 'Thống kê hàng đợi',
    systemTitle: 'Thiết lập hệ thống',
    systemSave: 'Lưu thiết lập',
    auditLogsTitle: 'Nhật ký hoạt động',
    actionApprove: 'Duyệt',
    actionReject: 'Từ chối',
    actionHide: 'Ẩn',
    allStatus: 'Tất cả trạng thái',
    allActions: 'Tất cả thao tác',
  },
} as const

export function useCopy() {
  const language = usePreferencesStore((state) => state.language)
  return copy[language as Language]
}
